project:
  type: book

book:
  title: "Dehazing Notebook"
  author: "Benjamin Poulin"
  chapters:
    - index.qmd
    - bibliography.qmd
    - part: "Progress"
      chapters:
        - 2025.06.27.qmd
        - 2025.07.11.qmd
        - 2025.07.31.qmd
    - references.qmd

bibliography: references.bib
csl: proceedings-of-the-ieee.csl

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



